### ISSUE TITLE
Features disabled when Trainer Menu is hidden

### ISSUE THREAD

**Issue by sondaismith** [gtav-ent/GTAV-EnhancedNativeTrainer#10]
If F4 is used to hide the menu while "Never Wanted" or other features are enabled, the feature is disabled until the menu is shown again.

Hiding the menu prevents the script from progressing to "update_features()" in the main() method in script.cpp.

**Comment by gtav-ent** [comment]
Unless you find otherwise, this was fixed in Release 10.
