### ISSUE TITLE
GTAV EnhancedNativeTrainer release #25 Not working

### ISSUE THREAD

**Issue by HvyMetal55** [gtav-ent/GTAV-EnhancedNativeTrainer#104]
![gtav-enhancednativetrainer 1](https://cloud.githubusercontent.com/assets/13227093/8558355/d219061a-24c0-11e5-81d5-754e7281cbe1.jpg)

I've done everything in accordance to the instructions. I'm unable to bring up the menu options when pressing F4. 

 GTAV EnhancedNativeTrainer release #24 works just fine. 

So I'm not sure what or if I'm doing something wrong.

**Comment by gtav-ent** [comment]
Your Script Hook DLLs look to be out of date & incompatible.

Get it from: http://www.dev-c.com/gtav/scripthookv/

(don't unpack NativeTrainer.asi as this replaces it)

**Comment by HvyMetal55** [comment]
That resolved the issue. Thanks so much.
