### ISSUE TITLE
*Someone* forgot to commit config_io.cpp

### ISSUE THREAD

**Issue by qaisjp** [gtav-ent/GTAV-EnhancedNativeTrainer#14]
I think...

**Comment by dratom** [comment]
Windows has a habit of ignoring blank files in archives. Try creating a blank txt file and renaming it to config_io.cpp.

**Comment by gtav-ent** [comment]
Sorry about that, VS is a bit weird sometimes. Added now.

**Comment by qaisjp** [comment]
Hey, I'm getting build errors relating to the MSXML parser. The Windows SDK has been installed and it seems to be linking correctly.

Here's the error: `Error	1	error C2039: 'DOMDocument30' : is not a member of 'MSXML2'	C:\Users\qaisjp\Downloads\ScriptHookV_SDK_1.0.350.2\samples\GTAV-EnhancedNativeTrainer\EnhancedNativeTrainer\config_io.cpp	28	1	EnhancedNativeTrainer
`

**Comment by qaisjp** [comment]
Oh and @dratom, I'm using "git pull" :)

**Comment by gtav-ent** [comment]
In the intermediate file EnhancedNativeTrainer\tmp\Release\msxml6.tlh, I have DOMDocument30, so can't explain what you're seeing. If 60 works (presumably meaning MSXML v6.0), then we can use that instead.

**Comment by qaisjp** [comment]
Hmm, here's my [msmxml6.tlh](https://a.pomf.se/jlcmcd.tlh), can't find DOMDocument30. :/

**Comment by qaisjp** [comment]
[DOMDocument60 is now used](https://github.com/gtav-ent/GTAV-EnhancedNativeTrainer/commit/08e374f6e9d2e500939ea777128e11111d34bed8#diff-c2ec16a8df2cd58649a81bf18e7adfd0R28)
