### ISSUE TITLE
Albany Stretch -> Dundreary Stretch

### ISSUE THREAD

**Issue by NJAldwin** [gtav-ent/GTAV-EnhancedNativeTrainer#18]
> The GTA V Stretch is a conversion of the Albany Washington, bearing the Albany badging, but is named the Dundreary Stretch, after the GTA IV rendition, based off of the Dundreary Admiral.

([from the wiki](http://gta.wikia.com/Stretch#HD_Universe))

The in-game caption calls the limo the Dundreary Stretch, so I'd propose changing the spawn entry from "Albany Stretch" to "Dundreary Stretch".

![271590_2015-05-10_00001](https://cloud.githubusercontent.com/assets/145036/7556824/e6ab1572-f74e-11e4-9360-a9a729fcaed3.png)

**Comment by gtav-ent** [comment]
Good spot, and fine by me - do you want to make the change yourself?

**Comment by qaisjp** [comment]
Please close
