### ISSUE TITLE
the project requires a license

### ISSUE THREAD

**Issue by qaisjp** [gtav-ent/GTAV-EnhancedNativeTrainer#19]

**Comment by gtav-ent** [comment]
Agreed, although I can't imagine anyone will be *too* fussed. Does anyone have any opinions? GPL suits me, since some of this work isn't ours in the first place.

**Comment by qaisjp** [comment]
MIT would be great, not really keen on copyleft licenses like GPL though
but it's not too much of an issue. Would have to check what the licence for
the original SDK is

**Comment by gtav-ent** [comment]
There isn't one, besides:

>Terms of use
>-	You are allowed to use this SDK only for writing scripts intended to work offline.
>-	You are not allowed to redistribute ScriptHookV.dll with your script plugins, 
>	provide the link to the latest runtime instead:
>	http://www.dev-c.com/gtav/scripthookv/

As I don't think selling trainers is very likely, the most likely issue here is someone taking this community work and bundling it into something that they don't release the source for, so personally I'm in favour of copyleft to keep it all open.

**Comment by qaisjp** [comment]
Hmmmm, fair enough.. we'll have to ask Alex what his licence is

**Comment by Kyle873** [comment]
I'd agree to go copyleft here. I've already seen people stealing code and incorporating it into their own trainers then selling them without actually contributing anything to the community.

**Comment by qaisjp** [comment]
Would be great if you referenced issues in your commits :) Took me a whole day to realise that a license was added :)

**Comment by gtav-ent** [comment]
To be a bit blunt, I've got more than enough to keep me busy here & elsewhere without cross-referencing everything. Some things are inevitably going to be less than optimal here! Generally I just try to give you what you ask for in the quickest workable way.
