### ISSUE TITLE
Commit/share Excel spreadsheets for peds & vehicles

### ISSUE THREAD

**Issue by gtav-ent** [gtav-ent/GTAV-EnhancedNativeTrainer#29]
The master data for skins & vehicles is really in a spreadsheet each, not the code, which is always made up of two big long lists (captions & values) that are hard to maintain, especially in A-Z order.

We need to find a way of sharing them so people can change it at source. Note that these are VBA macro books so you can C&P to arrays, thus Google Docs etc is not an option.

**Comment by qaisjp** [comment]
Why not just have xml files that are *somehow* read & compiled @ compile time?

**Comment by Kyle873** [comment]
Loading it along with the plugin isn't a bad idea. That way the end-user could make additions to it if something is missing instead of needing to wait for a new release.

**Comment by gtav-ent** [comment]
The point of the document is really to let us change things in the simplest manner (or add more attributes etc) rather than to let the end user do anything

**Comment by gtav-ent** [comment]
These are added.

**Comment by qaisjp** [comment]
No, as a resource, readable by the program but not the end user
