### ISSUE TITLE
Feature request: add controller support to keys

### ISSUE THREAD

**Issue by gtav-ent** [gtav-ent/GTAV-EnhancedNativeTrainer#39]
Controller support is required, and a Reddit user provides the following:

Through my experience with LUA scripts (mostly this mod), you can use the CONTROLS namespace to use gamepad controls:

if CONTROLS.IS_CONTROL_PRESSED(2,/*code*/)

Here's the list of codes:

A - 18
B - 45
X - 22
Y - 23
LB - 37
RB - 44
L2 - 10
R2 - 11
L3 - 28
R3 - 29
Select - 0
Start - Unknown

*D-Pad:*

Left - 15
Right - 74
Up - 27
Down - 19

*Left-Stick:*

Left - 34
Right - 9
Up - 32
Down - 8

*Right-Stick:*

Left - 5
Right - 1
Up - 3
Down - 2

**Comment by gtav-ent** [comment]
I will put in the support for definition in the XML, but I don't have a controller so will require a bit of support with testing it.

**Comment by qaisjp** [comment]
I have a ps3 controller, might be able to help

**Comment by Kyle873** [comment]
I can also help here if necessary. Got an old wired 360 controller I can test with.

**Comment by snckrz** [comment]
Got a wireless X360 Controller and a Xbox One (wired) controller. WIll gladly help.

**Comment by Neutrinobeam** [comment]
There are over 300 control codes. Here are IMO the most useful.

MenuDown = 187,					// ArrowDown + Controller Pad Down
MenuUp = 188,					// ArrowUp + Controller Pad Up
MenuLeft = 189,					// ArrowLeft + Controller Pad Left
MenuRight = 190,					// ArrowRight + Controller Pad Right
MenuAccept = 201,				        // Enter + NumPadEnter + Controller A
MenuCancel = 202,				        // Escape + Backspace + Controller B
SkipCutscene = 18,					//Space + Enter + Controller A + Left Mouse
MoveUp = 32, //268					// W + Controller Left Up
MoveDown = 33, //269				// S + Controller Left Down
MoveLeft = 34, //266				// A + Controller Left Left
MoveRight = 35, //267				// D + Controller Left Right
PhoneUp = 172,					// ArrowUp + Controller Pad Up
PhoneDown = 173,		    		        // ArrowDown + Controller Pad Down
PhoneLeft = 174,					// ArrowLeft + Controller Pad Left
PhoneRight = 175,					// ArrowRight + Controller Pad Right
PhoneSelect = 176,				        // Enter + MouseLeft + Controller A
PhoneCancel = 177,				// Escape + Backspace + MouseRight + Controller B

If you're curious about the rest, I pack a file documenting them with one of my mods https://www.gta5-mods.com/scripts/mod-menu-no-more-hotkeys.

**Comment by gtav-ent** [comment]
Those of you that offered to help, are you still reading this?

I have an XBone controller now, and the basics are working.

Can someone suggest a decent key scheme?

So far I have in mind:

- digital D-pad for menu up/down/left/right
- left trigger for back
- right trigger for select
- right shoulder + Y to bring up/hide trainer menu

Airbrake mode can follow along those lines.

I don't have a good proposal for vehicle rockets/boost/stop.

This is kind of all contingent on being able to stop the input straight going to the ordinary game functions when the menu is up etc. I haven't tried this yet, but it seems possible.

**Comment by Reck1501** [comment]
You can check the open source mods with controller support and see how they do it

**Comment by gtav-ent** [comment]
Technically doing it is fine, just now looking for some user feedback on what buttons / button combos would suit, as I haven't personally been using a controller to play, let alone with other mods

**Comment by Reck1501** [comment]
I'm sure alot of people would enjoy having controller support in the mod, including myself. So you should go ahead and do it :P

**Comment by gtav-ent** [comment]
Sounds good. Are the bumpers used for anything already?

**Comment by qaisjp** [comment]
I strongly suggest you use normal options:

- dpad
- x for confirm
- y for back

- select + y maybe for trainer?

**Comment by Reck1501** [comment]
Hm, I don't think so.

**Comment by qaisjp** [comment]
Okay, @reck1501, care to elaborate?

**Comment by Reck1501** [comment]
No, I was replying to gtav-ent's comment

**Comment by qaisjp** [comment]
Oh okay, @reck1501

**Comment by gtav-ent** [comment]
If that's the usual pattern then fair enough.

I tried doing this with CONTROLS::WHATEVER but it sucks - includes keyboard input, so makes a mess. Now instead we're going to use XInput directly. If we carry on like this, soon we'll have our own game.

**Comment by Reck1501** [comment]
Yes! And we inscribe upon the back; must not be used as a condom!
![image](https://cloud.githubusercontent.com/assets/10678035/8148524/acc38d58-12a1-11e5-9af0-9b9f0e4de6f7.png)

**Comment by gtav-ent** [comment]
The current commit is a half-decent attempt at controller support, if anyone feels like testing. I'll make a pre-release version soon.

**Comment by gtav-ent** [comment]
Please see the Releases page for the Update 23 pre-release, which I'd like some feedback on.
