### ISSUE TITLE
Refactor vehicle mod menu to match skin customiser

### ISSUE THREAD

**Issue by gtav-ent** [gtav-ent/GTAV-EnhancedNativeTrainer#43]
The vehicle mod menu currently gives all the options, and selecting a particular option cycles through those items. Sometimes there is only one item. Ideally the feature should be refactored to pick from the available set for the current vehicle.

There's a small extra complexity here in that the menu needs to go away or update when the vehicle is changed or exited.

Doing this will make it easy to add things that don't commonly apply to every vehicle, like liveries.

**Comment by gtav-ent** [comment]
All known features are added, with the exception of neon lights that need an RGB colour picker first, and will be a pain to add anyway.

This could do with a few more checks in some places, like not letting you try certain things on helicopters etc, but whatever.

**Comment by gtav-ent** [comment]
All done.

FYI, a menu interrupt capability has been added. This lets you poke a menu out of its while loop. For example, this is used when we want to get rid of the vehicle menus because the player has left the vehicle.

**Comment by dratom** [comment]
Thank You.
The menu interrupt is a major help all its own.

Also I wanted to say Thanks-a-bunch for your continued efforts in keeping this project both object oriented(ish) and mobile. You are a boss

I have some free time coming up and I hope to lend a hand.
