### ISSUE TITLE
Persistence capability - save state in a file/database

### ISSUE THREAD

**Issue by gtav-ent** [gtav-ent/GTAV-EnhancedNativeTrainer#52]
The trainer should be able to save its state - what modes are set, etc - so that it can be persisted between loads. It also then offers the ability to save user locations, car settings, skin choices, etc.

Using SQLite is probably a good bet for this.

**Comment by qaisjp** [comment]
I think SQLite would be a bit overpowered for a **relatively** simple thing like this - what about a simple settings XML file?

**Comment by gtav-ent** [comment]
We already have one of those for the key config, but based on that, SQLite is very likely simpler than reading and writing back out variable XML.

**Comment by qaisjp** [comment]
Having a database won't be user friendly either - if someone would like to directly edit their configuration they won't know what to do with a db, they can easily understand xml files.

**Comment by gtav-ent** [comment]
They're supposed to be able to edit the key config etc, which is going to remain in XML as it is already, but they're not supposed to be able to edit the persisted data. In fact it would probably be better if they couldn't.

**Comment by gtav-ent** [comment]
Very much work in progress, but we now have a database. The feature enablement values in script.cpp are persisted and loaded back. The rest, not so much yet.

**Comment by gtav-ent** [comment]
This as a general issue is complete. Plenty more things need persisting, but we now have the structure for it, so anything more can be raised as specific issues.
