### ISSUE TITLE
Investigation: disable restricted zones?

### ISSUE THREAD

**Issue by snckrz** [gtav-ent/GTAV-EnhancedNativeTrainer#61]
This is one feature that I am really missing :/ Would be awesome if you could implement a button to disable the restricted zones, so you won't get shot down. (As in director mode, but without using the actual director mode)

**Comment by gtav-ent** [comment]
I haven't seen an API for this, but if it works in Director Mode, then there's a possibility.

**Comment by qaisjp** [comment]
Doesn't "never wanted" work in there? Or decreasing your wanted level?
Unless you'd like to get wanted inside there on your own terms.

**Comment by gtav-ent** [comment]
'Never wanted' (actually the set-max-wanted-level-to-zero command within it) stops it setting a wanted level, but it doesn't stop you being shot down. Director Mode has an option that does that.

**Comment by snckrz** [comment]
On the X360 Version you could disable them with some Hex editing in the Script.rpf file. There are a few files that control the restricted areas. (they are even called after them (restrictedareas.yxc or re_zancudo.yxc dont know the exact names and file endings, but I can search them if that helps.))

**Comment by gtav-ent** [comment]
If you can provide all the info you can on that, it might lead somewhere.

**Comment by gtav-ent** [comment]
I had a quick look at the decompiled scripts and the most likely candidate for this control is probably:

if (GAMEPLAY::IS_BIT_SET(rPtr((&g_2407802) + 4131), 0) == 0)

but good luck figuring out the actual parameter value for that.

**Comment by snckrz** [comment]
Tbh I have no idea what you are talking about.
But this is the Mod I was talking about: http://www.se7ensins.com/forums/threads/s-p-release-no-siren-no-wanted-level-no-stars-at-army-base-airport-or-prision.1152392/#post-8958489

Currently it seems I deleted OpenIV for from HDD (for whatever reason), will comment after I found those files in the PC version.

**Comment by snckrz** [comment]
The Files are located in update/update.rpf/x64/levels/gta5/script/script_rel.rpf
The file names are the same, only the ending changed.

**Comment by gtav-ent** [comment]
The files are already decompiled for PC, I have those.

What might be interesting is if you can decompile the version you linked to.

**Comment by snckrz** [comment]
Sadly I lack the knowledge to do so. :/

**Comment by snckrz** [comment]
This might help: http://www.se7ensins.com/forums/threads/release-xsctoolbox-project-xsc-compiler-updated-6-2-14.1109926/

**Comment by gtav-ent** [comment]
Reading a few things elsewhere, the most likely way to make this work is to disable the other game script(s) that are responsible for it. There's an API for this but you need the names.

One to look at when I get time.

**Comment by snckrz** [comment]
Any updatess on this? I hadn't the time to check GTA out for a week or so because of schools n stuff. So whats the current state of progress on this? :)

**Comment by gtav-ent** [comment]
None, I'm on holiday :)

**Comment by gtav-ent** [comment]
Partly based on some of your info, I worked out how to do this - it'll probably be in the next update.
