### ISSUE TITLE
Vehicle paint: set menu index based on what paint is already applied

### ISSUE THREAD

**Issue by gtav-ent** [gtav-ent/GTAV-EnhancedNativeTrainer#65]
Where possible, opening the menus takes you to the option already applied - e.g. in the skin chooser, the head/shirt/legs drawable and texture that you're already using.

Vehicle paint should do this if possible to figure it out via API calls.

**Comment by TSM4278** [comment]
Good idea, that shouldn't be a problem to add. I'll look into it as soon as i get a chance.

**Comment by gtav-ent** [comment]
This is done in u26.
