### ISSUE TITLE
Determine weapon mod names/hashes

### ISSUE THREAD

**Issue by gtav-ent** [gtav-ent/GTAV-EnhancedNativeTrainer#70]
Some of these can be worked out from the decompiled scripts, but I guess not all.

Can we find a list?

Hashes in the decompiled scripts:

0x837445AA
0x359B7AAE
0x7BC4CDDC
0x837445AA

**Comment by TSM4278** [comment]
I was actually working on a weapon mod menu that is still a WIP, but you can see the vanilla weapon mod names in there. Here's a link to the file. https://github.com/TSM4278/GTAV-EnhancedNativeTrainer/blob/weaponmodmenu/EnhancedNativeTrainer/weaponmodmenu.cpp

**Comment by gtav-ent** [comment]
Brilliant! Had the fear that I'd have to brute force it or something. Where did you get them?

**Comment by TSM4278** [comment]
I got them from the weapons.meta file.
