### ISSUE TITLE
Better highlight multiple pages in menus

### ISSUE THREAD

**Issue by gtav-ent** [gtav-ent/GTAV-EnhancedNativeTrainer#73]
No numpty can figure out that some of the menus are paginated, e.g. where 'fast run' has gone.

Do something to highlight the pagination, e.g. different colour page numbers or a menu footer.

**Comment by JakobTischler** [comment]
I like the color highlight idea; you could also add an ellipsis at the end (bottom) of the current page.

**Comment by qaisjp** [comment]
Yes, an ellipsis would be a great idea.

Eventually scrolling could be added, I can have a stab at this in about two weeks time when I'm done with exams.

**Comment by gtav-ent** [comment]
Done for now.
