### ISSUE TITLE
c_str() calls on temporary values

### ISSUE THREAD

**Issue by ChrisTX** [gtav-ent/GTAV-EnhancedNativeTrainer#78]
I noticed while compiling today that some expressions in for example `database.cpp` (e.g. lines 164, 197, 242) and `menu_functions.h` (lines 267, 408, 443) are of the form `ss.str().c_str()` where `ss` is a `std::stringstream`.

The value returned by `.str()` however is a *temporary* value (prvalue) of type `std::string` and not a reference. Namely, `.c_str()` will point to the buffer of a temporary object that can be destructed immediately after the return of the value in which case the pointer would be dangling. Visual C++ tends to place the call to the destructor immediately afterwards, too - so it is not merely a matter of formal correctness, but of actual importance.

In order to fix this, it's necessary to first have the returned string assigned to an lvalue and then call `.c_str()` on that lvalue, i.e. `auto mystr = ss.str(); somefunction(mystr.c_str())`. In this case, the validity of the pointer is tied to the lifetime of `mystr` - thus the call is operating on a valid pointer.

Please note that I'm not familiar with the code base and do not know if any similar patterns exist elsewhere in the code.

EDIT: Oh and please replace `strlen(ss.str().c_str())` by `mystr.length()`.

**Comment by gtav-ent** [comment]
It's a fair cop. I wrote this code & ran into string corruption when developing it, but by having the statements separated. The form above appears to work in its current toolchain but it's certainly not good code.

**Comment by gtav-ent** [comment]
The above is resolved, and a quick search doesn't reveal any more.

**Comment by qaisjp** [comment]
[Or you can just do this](https://github.com/qaisjp/GTAV-EnhancedNativeTrainer/commit/d2cd5eeddebf1214db2d60fba8045fb3ca618696#diff-7897794b5d0dcc2d2c0a867f254b3564R136)

`&str[0u]` where `std::string str`

**Comment by ChrisTX** [comment]
@qaisjp There's no reason to do that. It will work, but there's `.data()` to get exactly that value and it's easier to read.

Moreover, before C++11, `.c_str()` and `.data()` could do in theory something different and the underlying string was not required to be null terminated - since C++11, the standard requires the two functions to have the same behavior.
