### ISSUE TITLE
Crashes for some users on startup

### ISSUE THREAD

**Issue by gtav-ent** [gtav-ent/GTAV-EnhancedNativeTrainer#79]
Versions 16 onwards crash for some users on game start. I've tried to add some diagnostics but they're not turning up anything as yet.

Does anyone here have this problem?

**Comment by dratom** [comment]
I haven't had this problem but I did notice a large number of people reporting issues with the latest scripthook update. It could be unrelated or at least not related to the b revision of of the scripthook. I have not personally tried using the newer sdk, or the new asi loader (that is assuming that the asi loader was updated(again i haven't tested it or looking into it)). There was also a large update to OpenIV. Im not sure if either of these could be related but if you diagnostics continue to produce no leads then it may be a conflict with one of the above mentioned updates.

**Comment by gtav-ent** [comment]
I strongly suspect it's the introduction of the database stuff, as they can downgrade to v15 and get rid of their problems, but I don't have any leads as yet and obviously can't trigger it on my own system.

**Comment by gtav-ent** [comment]
This seems to have been file permissions related. We should consider writing stuff to somewhere else, e.g. %APPDATA%, although potentially it just makes supporting people harder.

**Comment by gtav-ent** [comment]
The database is now written to an %APPDATA% based location, which hopefully resolves this.

**Comment by Reck1501** [comment]
Even with these changes, it's still crashing for me

**Comment by gtav-ent** [comment]
Have a look at:

http://gtaforums.com/topic/789786-vrelwip-enhanced-native-trainer/?p=1067564091

and see if you can do the same for your crash.

**Comment by gtav-ent** [comment]
Also, other things that you should check/report back on:
- your Script Hook is up to date
- it's not a cracked version of the game, which probably isn't compatible
- other mods work OK
- you have the XML file unpacked (currently to the game dir)

**Comment by Reck1501** [comment]
My scripthook is up to date, I run the digitally purchased retail version of the game, I haven't included the XML file as I thought it would be automaticly generated, I'll add it to the game folder and come back with the results

**Comment by Reck1501** [comment]
It didn't work, neither did the debug version you linked

**Comment by Reck1501** [comment]
When I use OpenVHook, it doesn't crash. It appears to be a problem with ScriptHookV

**Comment by Reck1501** [comment]
Or not.. It appears to be crashing if EnhancedNativeTrainer loads before the game has fully loaded storymode

**Comment by gtav-ent** [comment]
If you're not getting any kind of debug output as per the linked post, it suggests something is fundamentally wrong with your setup.

It's built against Script Hook V, and specifically, the release I made this morning is built against the latest one.

What do the other logs like ScriptHookV.log and asiloader.log say?

**Comment by gtav-ent** [comment]
It's been a week without anyone complaining so I'm closing the issue.
