### ISSUE TITLE
Disable Player Helmet Option

### ISSUE THREAD

**Issue by dratom** [gtav-ent/GTAV-EnhancedNativeTrainer#87]
An option to stop the player's ped from putting on a helmet would make a nice addition to the vehicle menu( usually occurs after idling on a motorcycle ). I have not seen an API that might be used for this so I'm not even sure it's possible atm.

**Comment by gtav-ent** [comment]
A per-frame call to:

PLAYER::REMOVE_PLAYER_HELMET(Player player, BOOL p2)

?

I haven't tried it. This might result in conflict with the game, i.e. constantly being given and dropping helmets.

**Comment by dratom** [comment]
Hmm. I really should have checked native db first since I was not ever aware of that api. Ill give it a go but it will likely to be a situation like you guessed with the helmet being reapplied and removed every few seconds.

**Comment by dratom** [comment]
PED::SET_PED_HELMET(ped, bool)
false = player does not put on a helmet
true = player put on a helmet

Is a static toggle(only need to set it once)

**Comment by gtav-ent** [comment]
Done, by sondaismith. Added to release 23.
