### ISSUE TITLE
Vehicle/skin previews in menu

### ISSUE THREAD

**Issue by gtav-ent** [gtav-ent/GTAV-EnhancedNativeTrainer#88]
Someone posted this idea:

http://pixs.ru/showimage/Bezimyanni_6939760_17629841.jpg

which isn't the first time it's been floated.

I originally thought this would require extra graphics, but thinking about it, the game has a car supermarket website that features most vehicles and pictures of each.

Equally the pause menu features a mini-graphic of each ped.

If these can be brought to life and drawn to the screen, that'd be the icing on the cake.

**Comment by faceofwin** [comment]
all list of cars i get here http://rockstargame.ru/gta-v/transport/

**Comment by gtav-ent** [comment]
This is going into u25 and about 50% of vehicles have images using in-game assets. The rest will have to wait until Script Hook adds the ability to load textures not just from files but embedded in DLLs.

**Comment by gtav-ent** [comment]
This got 100% coverage in Update 25.
