### ISSUE TITLE
Vehicle speed boost stalls

### ISSUE THREAD

**Issue by dratom** [gtav-ent/GTAV-EnhancedNativeTrainer#89]
If vehicle invincibility and vehicle speed boost are both enabled while speed boost acceleration key is being held the player's vehicle's speed will drop to 0.0 roughly every 3 seconds.

My guess it happens when the API that was recently added to vehicle invincibility to keep the vehicle from showing cosmetic damage is reset every few frames. 
Setting the API only when invincibility is toggled might remedy this. It might be that it needs to be set every time the player changes vehicles.

**Comment by gtav-ent** [comment]
This was fixed in a re-release of 22.

Periodically calling VEHICLE::SET_FIXED() caused these problems, so I found an unnamed native that roughly corresponds to 'is vehicle damaged', and used that as a condition.

I've just checked in those changes.

**Comment by gtav-ent** [comment]
Noone has actually confirmed this works nicely for them though, so if you or anyone else can, we can close the issue.
