### ISSUE TITLE
Invincibility not working

### ISSUE THREAD

**Issue by raxixor** [gtav-ent/GTAV-EnhancedNativeTrainer#90]
It worked for a while after installing it, but now it is not working at all. Only vehicle invulnerability works.

**Comment by gtav-ent** [comment]
Do you have any other mods installes?

**Comment by raxixor** [comment]
A lot of mods

**Comment by gtav-ent** [comment]
Then that's your problem. One of them is conflicting, i.e. we apply invincibility once per frame and they undo it. Remove them until you figure out what. It'd be interesting to know which.

**Comment by raxixor** [comment]
I have already done that, it did not work even with no more whatsoever other than itself.

**Comment by gtav-ent** [comment]
I tested this, looked at the code and I'm fairly sure any problem has to be at your end. If you can show otherwise, I'll gladly reopen the issue.
