### ISSUE TITLE
I think the controller keys should be these keys for boost and stop by default.

### ISSUE THREAD

**Issue by McKiller5252** [gtav-ent/GTAV-EnhancedNativeTrainer#92]
When your trying to Vehicle boost its kind of annoying so see the character to get out its crosshair to shoot and the camera to zoom in slightly and i think the default key for Vehicle boost should be just "BUTTON_A" and "DPAD_RIGHT" to stop the car

Let me know what you think ENT. 

Thanks. :)

**Comment by Reck1501** [comment]
Personally, I prefer the way they are now, but if possible I believe ENT should implement the config of the controller setup in the config file, allowing people to make their own controller controls.

**Comment by McKiller5252** [comment]
Reck, You can already change the controller buttons in the config file if you wanted to, But im talking about making the buttons there by default

**Comment by gtav-ent** [comment]
I don't mind changing them once, but I don't want to keep doing it, as it'll be confusing to users now that it's been released.

If popular consensus is for some other setup, fine, but I'm not sure how you might find that out.

**Comment by Reck1501** [comment]
If you're able to change them by yourself already, why not just do that instead of requesting them to be changed? :P
